name: store_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  chips_choice: ^3.0.1
  cupertino_icons: ^1.0.0
  dio: ^5.3.3
  dot_navigation_bar: ^1.0.2
  flashy_tab_bar2: ^0.0.6
  flutter:
    sdk: flutter
  modal_progress_hud_nsn: ^0.4.0
  persistent_bottom_nav_bar_v2: ^4.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
